[phases.setup]
aptPkgs = [
    "python3.9",
    "python3.9-dev",
    "python3-pip",
    "build-essential",
    "gcc"
]

[phases.install]
cmds = [
    "python3.9 -m pip install --upgrade pip",
    "python3.9 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.9 -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"