[phases.setup]
aptPkgs = [
    "python3.9",
    "python3.9-dev",
    "python3-pip",
    "build-essential",
    "gcc"
]
cmds = [
    "export PATH=/usr/bin/python3.9:$PATH",
    "python3.9 --version"  # Confirm Python 3.9 is available
]

[phases.install]
cmds = [
    "python3.9 -m pip install --upgrade pip",
    "python3.9 -m pip install -r requirements.txt"
]
