[phases.setup]
aptPkgs = [
    "python3.9",
    "python3.9-dev",
    "python3-pip",
    "build-essential",
    "gcc"
]

cmds = [
    "python3.9 --version",  # Ensure Python is installed
    "export PATH=/usr/bin/python3.9:$PATH"  # Explicitly add Python to PATH
]

[phases.install]
cmds = [
    "python3.9 -m pip install --upgrade pip",
    "python3.9 -m pip install -r requirements.txt"
]
[start]
cmd = "python3.9 start.py"